<a href="https://colab.research.google.com/github/YamilaP25/Actividad-7-Regresi-n-Log-stica/blob/main/Actividad_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#caegar librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
from google.colab import files
files.upload()

In [ ]:
df = pd.read_csv('BD_Socio formador (TrainingDataComplete).csv', index_col= 'Id')

df.isnull().sum()

Income               0
Age                  0
Experience           0
Married/Single       0
House_Ownership      0
Car_Ownership        0
Profession           0
CITY                 0
STATE                0
CURRENT_JOB_YRS      0
CURRENT_HOUSE_YRS    0
Risk_Flag            0
dtype: int64

In [ ]:
df.head()

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                          
1   1303834   23           3         single          rented            no   
2   7574516   40          10         single          rented            no   
3   3991815   66           4        married          rented            no   
4   6256451   41           2         single          rented           yes   
5   5768871   47          11         single          rented            no   

             Profession                 CITY           STATE  CURRENT_JOB_YRS  \
Id                                                                              
1   Mechanical_engineer                 Rewa  Madhya_Pradesh                3   
2    Software_Developer             Parbhani     Maharashtra                9   
3      Technical_writer            Alappuzha          Kerala                4   
4    Software_Developer          Bhubaneswar          Odisha                2   
5         Civil_servant  Tiruchirappalli[10]      Tamil_Nadu                3   

    CURRENT_HOUSE_YRS  Risk_Flag  
Id                                
1                  13          0  
2                  13          0  
3                  10          0  
4                  12          1  
5                  14          1

#**CASO 1**

**Reemplazar valores**

In [ ]:
df1 = df.copy()
#Convierto una variable a dicotómica
filtro = df1[(df1['STATE'] == 'Uttar_Pradesh') | (df1['STATE'] == 'Maharashtra')]
filtro.head()

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                          
2   7574516   40          10         single          rented            no   
6   6915937   64           0         single          rented            no   
18  3666346   56          12         single          rented            no   
35  9086933   55           7         single          rented            no   
37  9625415   77          15        married          rented            no   

                Profession        CITY          STATE  CURRENT_JOB_YRS  \
Id                                                                       
2       Software_Developer    Parbhani    Maharashtra                9   
6            Civil_servant     Jalgaon    Maharashtra                0   
18              Politician    Bhusawal    Maharashtra               12   
35  Air_traffic_controller  Saharanpur  Uttar_Pradesh                7   
37               Secretary    Amravati    Maharashtra                9   

    CURRENT_HOUSE_YRS  Risk_Flag  
Id                                
2                  13          0  
6                  12          0  
18                 11          1  
35                 13          0  
37                 10          0

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = filtro[['Income', 'Age', 'CURRENT_HOUSE_YRS']]
Var_Dep = filtro['STATE']

#Redefinimos las variables
X = Vars_Indep
y = Var_Dep

from scipy.sparse import random
#Dividimos el conjunto de datos en la parte de entrenamiento y de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.45, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables 'X' tanto de entrenamiento como de prueba, utilizamos
X_train = escalar.fit_transform(X_train)
X_test = escalar.fit_transform(X_test)

#Definimos el algorítmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test)

from sklearn.metrics import classification_report
reporte = classification_report(y_test, y_pred, labels = ['Uttar_Pradesh','Maharashtra'])
print(reporte)

               precision    recall  f1-score   support

Uttar_Pradesh       0.53      0.87      0.66     12730
  Maharashtra       0.52      0.15      0.24     11553

     accuracy                           0.53     24283
    macro avg       0.52      0.51      0.45     24283
 weighted avg       0.52      0.53      0.46     24283



In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

#Cálculo de la presición del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average = 'binary', pos_label = 'Uttar_Pradesh')
print('\nPrecisión del modelo:')
print(precision)

#Calculo de exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculo de sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average = 'binary', pos_label = 'Uttar_Pradesh')
print('\nSensibilidad del modelo:')
print(sensibilidad)

#El puntaje F1 que es una combinacion entre la precisión y sensibilidad, para esto importamos f1_score
#Cálculo del puntaje F1 del modelo
from sklearn.metrics import f1_score
puntajef1 = f1_score(y_test, y_pred, average = 'binary', pos_label = 'Uttar_Pradesh')
print('\nPuntaje F1 del modelo:')
print(puntajef1)

Matriz de confusión:
[[ 1783  9770]
 [ 1672 11058]]

Precisión del modelo:
0.5309199154983676

Exactitud del modelo:
0.5288061606885476

Sensibilidad del modelo:
0.8686567164179104

Puntaje F1 del modelo:
0.6590380833184337


#**CASO 2**

**Reemplazar valores**

In [ ]:
#Convierto una variable a dicotómica
filtro = df[(df['CURRENT_HOUSE_YRS'] == 13) | (df['CURRENT_HOUSE_YRS'] == 10)]
filtro.head()

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                          
1   1303834   23           3         single          rented            no   
2   7574516   40          10         single          rented            no   
3   3991815   66           4        married          rented            no   
10  8964846   23          12         single          rented            no   
14  8043880   57          12         single          rented            no   

             Profession        CITY           STATE  CURRENT_JOB_YRS  \
Id                                                                     
1   Mechanical_engineer        Rewa  Madhya_Pradesh                3   
2    Software_Developer    Parbhani     Maharashtra                9   
3      Technical_writer   Alappuzha          Kerala                4   
10            Architect  Karimnagar       Telangana                5   
14    Financial_Analyst      Kollam          Kerala                8   

    CURRENT_HOUSE_YRS  Risk_Flag  
Id                                
1                  13          0  
2                  13          0  
3                  10          0  
10                 13          0  
14                 10          0

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = filtro[['Income', 'Age']]
Var_Dep = filtro['CURRENT_HOUSE_YRS']

#Redefinimos las variables
X = Vars_Indep
y = Var_Dep

from scipy.sparse import random
#Dividimos el conjunto de datos en la parte de entrenamiento y de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.5, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables 'X' tanto de entrenamiento como de prueba, utilizamos
X_train = escalar.fit_transform(X_train)
X_test = escalar.fit_transform(X_test)

#Definimos el algorítmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test)

from sklearn.metrics import classification_report
reporte = classification_report(y_test, y_pred, labels = [13,10])
print(reporte)

              precision    recall  f1-score   support

          13       0.51      0.86      0.64     25321
          10       0.49      0.14      0.22     24346

    accuracy                           0.51     49667
   macro avg       0.50      0.50      0.43     49667
weighted avg       0.50      0.51      0.43     49667



In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

#Cálculo de la presición del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average = 'binary', pos_label = 13)
print('\nPrecisión del modelo:')
print(precision)

#Calculo de exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculo de sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average = 'binary', pos_label = 13)
print('\nSensibilidad del modelo:')
print(sensibilidad)

#El puntaje F1 que es una combinacion entre la precisión y sensibilidad, para esto importamos f1_score
#Cálculo del puntaje F1 del modelo
from sklearn.metrics import f1_score
puntajef1 = f1_score(y_test, y_pred, average = 'binary', pos_label = 13)
print('\nPuntaje F1 del modelo:')
print(puntajef1)

Matriz de confusión:
[[ 3412 20934]
 [ 3576 21745]]

Precisión del modelo:
0.5095011598209892

Exactitud del modelo:
0.5065133791048382

Sensibilidad del modelo:
0.858773350183642

Puntaje F1 del modelo:
0.6395588235294117


#**CASO 3**

**Reemplazar valores**

In [ ]:
#Convierto una variable a dicotómica
filtro = df[(df['CURRENT_JOB_YRS'] == 5) | (df['CURRENT_JOB_YRS'] == 6)]
filtro.head()

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                          
10  8964846   23          12         single          rented            no   
15  9420838   48           6         single          rented            no   
19  2241112   28           8         single          rented            no   
24  9236505   36          19         single          rented            no   
27  6063428   38           6        married          rented            no   

           Profession        CITY           STATE  CURRENT_JOB_YRS  \
Id                                                                   
10          Architect  Karimnagar       Telangana                5   
15   Technical_writer     Madurai      Tamil_Nadu                6   
19     Police_officer       Sirsa         Haryana                6   
24  Chemical_engineer      Ongole  Andhra_Pradesh                6   
27            Dentist    Ambattur      Tamil_Nadu                6   

    CURRENT_HOUSE_YRS  Risk_Flag  
Id                                
10                 13          0  
15                 10          1  
19                 14          0  
24                 14          0  
27                 13          0

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = filtro[['Income', 'Age']]
Var_Dep = filtro['CURRENT_JOB_YRS']

#Redefinimos las variables
X = Vars_Indep
y = Var_Dep

from scipy.sparse import random
#Dividimos el conjunto de datos en la parte de entrenamiento y de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables 'X' tanto de entrenamiento como de prueba, utilizamos
X_train = escalar.fit_transform(X_train)
X_test = escalar.fit_transform(X_test)

#Definimos el algorítmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test)

from sklearn.metrics import classification_report
reporte = classification_report(y_test, y_pred, labels = [5,6])
print(reporte)

              precision    recall  f1-score   support

           5       0.52      0.96      0.67      7505
           6       0.56      0.06      0.10      7070

    accuracy                           0.52     14575
   macro avg       0.54      0.51      0.39     14575
weighted avg       0.54      0.52      0.40     14575



In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

#Cálculo de la presición del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average = 'binary', pos_label = 5)
print('\nPrecisión del modelo:')
print(precision)

#Calculo de exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculo de sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average = 'binary', pos_label = 5)
print('\nSensibilidad del modelo:')
print(sensibilidad)

#El puntaje F1 que es una combinacion entre la precisión y sensibilidad, para esto importamos f1_score
#Cálculo del puntaje F1 del modelo
from sklearn.metrics import f1_score
puntajef1 = f1_score(y_test, y_pred, average = 'binary', pos_label = 5)
print('\nPuntaje F1 del modelo:')
print(puntajef1)

Matriz de confusión:
[[7189  316]
 [6671  399]]

Precisión del modelo:
0.5186868686868686

Exactitud del modelo:
0.5206174957118354

Sensibilidad del modelo:
0.9578947368421052

Puntaje F1 del modelo:
0.6729698104376316


#**CASO 4**

**Reemplazar valores**

In [ ]:
#Convierto una variable a dicotómica
filtro = df[(df['Profession'] == 'Physician') | (df['Profession'] == 'Statistician')]
filtro.head()

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                           
13   9120988   28           9         single          rented            no   
30   4386333   31          16         single          rented            no   
90   6097344   27          16         single          rented           yes   
99   5083653   35          14         single          rented           yes   
124  9867887   79           9         single          rented            no   

       Profession       CITY       STATE  CURRENT_JOB_YRS  CURRENT_HOUSE_YRS  \
Id                                                                             
13      Physician  Erode[17]  Tamil_Nadu                9                 12   
30      Physician    Shimoga   Karnataka                3                 12   
90   Statistician   Kottayam      Kerala               10                 14   
99   Statistician   Ambattur  Tamil_Nadu               12                 11   
124     Physician     Chapra       Bihar                4                 12   

     Risk_Flag  
Id              
13           0  
30           0  
90           0  
99           0  
124          0

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = filtro[['Income', 'Age', 'Experience']]
Var_Dep = filtro['Profession']

#Redefinimos las variables
X = Vars_Indep
y = Var_Dep

from scipy.sparse import random
#Dividimos el conjunto de datos en la parte de entrenamiento y de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables 'X' tanto de entrenamiento como de prueba, utilizamos
X_train = escalar.fit_transform(X_train)
X_test = escalar.fit_transform(X_test)

#Definimos el algorítmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test)

from sklearn.metrics import classification_report
reporte = classification_report(y_test, y_pred, labels = ['Physician','Statistician'])
print(reporte)

              precision    recall  f1-score   support

   Physician       0.51      0.69      0.58      1759
Statistician       0.52      0.33      0.41      1770

    accuracy                           0.51      3529
   macro avg       0.51      0.51      0.49      3529
weighted avg       0.51      0.51      0.49      3529



In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

#Cálculo de la presición del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average = 'binary', pos_label = 'Physician')
print('\nPrecisión del modelo:')
print(precision)

#Calculo de exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculo de sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average = 'binary', pos_label = 'Physician')
print('\nSensibilidad del modelo:')
print(sensibilidad)

#El puntaje F1 que es una combinacion entre la precisión y sensibilidad, para esto importamos f1_score
#Cálculo del puntaje F1 del modelo
from sklearn.metrics import f1_score
puntajef1 = f1_score(y_test, y_pred, average = 'binary', pos_label = 'Physician')
print('\nPuntaje F1 del modelo:')
print(puntajef1)

Matriz de confusión:
[[1206  553]
 [1178  592]]

Precisión del modelo:
0.5058724832214765

Exactitud del modelo:
0.509492774156985

Sensibilidad del modelo:
0.6856168277430358

Puntaje F1 del modelo:
0.5821868211440985


#**CASO 5**

**Reemplazar valores**

In [ ]:
#Convierto una variable a dicotómica
filtro = df[(df['CITY'] == 'Vijayanagaram') | (df['CITY'] == 'Bhopal')]
filtro.head()

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                           
219  7357515   50          13         single          rented           yes   
233  1126863   43           1         single          rented            no   
236  7167762   49          14         single          rented            no   
336    67428   49          12         single          rented            no   
439  9078403   25          18        married          rented            no   

              Profession           CITY           STATE  CURRENT_JOB_YRS  \
Id                                                                         
219     Fashion_Designer         Bhopal  Madhya_Pradesh                7   
233  Mechanical_engineer  Vijayanagaram  Andhra_Pradesh                1   
236          Firefighter         Bhopal  Madhya_Pradesh               12   
336            Scientist  Vijayanagaram  Andhra_Pradesh               10   
439             Official  Vijayanagaram  Andhra_Pradesh                9   

     CURRENT_HOUSE_YRS  Risk_Flag  
Id                                 
219                 14          0  
233                 11          0  
236                 14          1  
336                 11          0  
439                 12          0

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = filtro[['Income', 'Age', 'Risk_Flag']]
Var_Dep = filtro['CITY']

#Redefinimos las variables
X = Vars_Indep
y = Var_Dep

from scipy.sparse import random
#Dividimos el conjunto de datos en la parte de entrenamiento y de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables 'X' tanto de entrenamiento como de prueba, utilizamos
X_train = escalar.fit_transform(X_train)
X_test = escalar.fit_transform(X_test)

#Definimos el algorítmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test)

from sklearn.metrics import classification_report
reporte = classification_report(y_test, y_pred, labels = ['Vijayanagaram','Bhopal'])
print(reporte)

               precision    recall  f1-score   support

Vijayanagaram       0.49      0.70      0.58       370
       Bhopal       0.49      0.28      0.36       371

     accuracy                           0.49       741
    macro avg       0.49      0.49      0.47       741
 weighted avg       0.49      0.49      0.47       741



In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

#Cálculo de la presición del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average = 'binary', pos_label = 'Vijayanagaram')
print('\nPrecisión del modelo:')
print(precision)

#Calculo de exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculo de sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average = 'binary', pos_label = 'Vijayanagaram')
print('\nSensibilidad del modelo:')
print(sensibilidad)

#El puntaje F1 que es una combinacion entre la precisión y sensibilidad, para esto importamos f1_score
#Cálculo del puntaje F1 del modelo
from sklearn.metrics import f1_score
puntajef1 = f1_score(y_test, y_pred, average = 'binary', pos_label = 'Vijayanagaram')
print('\nPuntaje F1 del modelo:')
print(puntajef1)

Matriz de confusión:
[[105 266]
 [111 259]]

Precisión del modelo:
0.49333333333333335

Exactitud del modelo:
0.49122807017543857

Sensibilidad del modelo:
0.7

Puntaje F1 del modelo:
0.5787709497206703


#**CASO 6**

In [ ]:
#Convierto una variable a dicotómica
filtro = df[(df['Profession'] == 'Web_designer') | (df['Profession'] == 'Psychologist')]
filtro.head()

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                           
55   1213131   67           8         single          rented            no   
103  4417164   42          12         single          rented            no   
122  8312895   35          12         single          rented            no   
134  9397962   58           3        married          rented            no   
135  3643187   77          20         single          rented            no   

       Profession        CITY          STATE  CURRENT_JOB_YRS  \
Id                                                              
55   Psychologist    Agartala        Tripura                8   
103  Web_designer     Vellore     Tamil_Nadu                8   
122  Psychologist   Bhagalpur          Bihar               11   
134  Psychologist  Saharanpur  Uttar_Pradesh                3   
135  Web_designer     Bellary      Karnataka               12   

     CURRENT_HOUSE_YRS  Risk_Flag  
Id                                 
55                  11          0  
103                 14          0  
122                 14          0  
134                 14          0  
135                 14          0

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = filtro[['Income', 'Age', 'Experience']]
Var_Dep = filtro['Profession']

#Redefinimos las variables
X = Vars_Indep
y = Var_Dep

from scipy.sparse import random
#Dividimos el conjunto de datos en la parte de entrenamiento y de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables 'X' tanto de entrenamiento como de prueba, utilizamos
X_train = escalar.fit_transform(X_train)
X_test = escalar.fit_transform(X_test)

#Definimos el algorítmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test)

from sklearn.metrics import classification_report
reporte = classification_report(y_test, y_pred, labels = ['Web_designer','Psychologist'])
print(reporte)

              precision    recall  f1-score   support

Web_designer       0.56      0.52      0.54      1664
Psychologist       0.53      0.57      0.55      1573

    accuracy                           0.55      3237
   macro avg       0.55      0.55      0.55      3237
weighted avg       0.55      0.55      0.55      3237



In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

#Cálculo de la presición del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average = 'binary', pos_label = 'Web_designer')
print('\nPrecisión del modelo:')
print(precision)

#Calculo de exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculo de sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average = 'binary', pos_label = 'Web_designer')
print('\nSensibilidad del modelo:')
print(sensibilidad)

#El puntaje F1 que es una combinacion entre la precisión y sensibilidad, para esto importamos f1_score
#Cálculo del puntaje F1 del modelo
from sklearn.metrics import f1_score
puntajef1 = f1_score(y_test, y_pred, average = 'binary', pos_label = 'Web_designer')
print('\nPuntaje F1 del modelo:')
print(puntajef1)

Matriz de confusión:
[[897 676]
 [792 872]]

Precisión del modelo:
0.5633074935400517

Exactitud del modelo:
0.5464936669755946

Sensibilidad del modelo:
0.5240384615384616

Puntaje F1 del modelo:
0.5429638854296389


#**CASO 7**

In [ ]:
#Convierto una variable a dicotómica
filtro = df[(df['CURRENT_HOUSE_YRS'] == 11) | (df['CURRENT_HOUSE_YRS'] == 12)]
filtro.head()

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                          
4   6256451   41           2         single          rented           yes   
6   6915937   64           0         single          rented            no   
7   3954973   58          14        married          rented            no   
9   7566849   24          17         single          rented           yes   
11  4634680   78           7         single          rented            no   

            Profession         CITY        STATE  CURRENT_JOB_YRS  \
Id                                                                  
4   Software_Developer  Bhubaneswar       Odisha                2   
6        Civil_servant      Jalgaon  Maharashtra                0   
7            Librarian     Tiruppur   Tamil_Nadu                8   
9     Flight_attendant      Kota[6]    Rajasthan               11   
11    Flight_attendant  Hajipur[31]        Bihar                7   

    CURRENT_HOUSE_YRS  Risk_Flag  
Id                                
4                  12          1  
6                  12          0  
7                  12          0  
9                  11          0  
11                 12          0

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = filtro[['Income', 'Age', 'Risk_Flag']]
Var_Dep = filtro['CURRENT_HOUSE_YRS']

#Redefinimos las variables
X = Vars_Indep
y = Var_Dep

from scipy.sparse import random
#Dividimos el conjunto de datos en la parte de entrenamiento y de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables 'X' tanto de entrenamiento como de prueba, utilizamos
X_train = escalar.fit_transform(X_train)
X_test = escalar.fit_transform(X_test)

#Definimos el algorítmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test)

from sklearn.metrics import classification_report
reporte = classification_report(y_test, y_pred, labels = [11,12])
print(reporte)

              precision    recall  f1-score   support

          11       0.51      0.55      0.53     15539
          12       0.51      0.46      0.48     15561

    accuracy                           0.51     31100
   macro avg       0.51      0.51      0.51     31100
weighted avg       0.51      0.51      0.51     31100



In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

#Cálculo de la presición del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average = 'binary', pos_label = 12)
print('\nPrecisión del modelo:')
print(precision)

#Calculo de exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculo de sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average = 'binary', pos_label = 12)
print('\nSensibilidad del modelo:')
print(sensibilidad)

#El puntaje F1 que es una combinacion entre la precisión y sensibilidad, para esto importamos f1_score
#Cálculo del puntaje F1 del modelo
from sklearn.metrics import f1_score
puntajef1 = f1_score(y_test, y_pred, average = 'binary', pos_label = 12)
print('\nPuntaje F1 del modelo:')
print(puntajef1)

Matriz de confusión:
[[8589 6950]
 [8362 7199]]

Precisión del modelo:
0.5087992084246237

Exactitud del modelo:
0.5076527331189711

Sensibilidad del modelo:
0.46263093631514685

Puntaje F1 del modelo:
0.4846179737462134


#**CASO 8**

In [ ]:
#Convierto una variable a dicotómica
filtro = df[(df['CURRENT_JOB_YRS'] == 3) | (df['CURRENT_JOB_YRS'] == 4)]
filtro.head()

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                          
1   1303834   23           3         single          rented            no   
3   3991815   66           4        married          rented            no   
5   5768871   47          11         single          rented            no   
12  6623263   22           4         single          rented            no   
22  6506739   50           4         single          rented            no   

             Profession                 CITY           STATE  CURRENT_JOB_YRS  \
Id                                                                              
1   Mechanical_engineer                 Rewa  Madhya_Pradesh                3   
3      Technical_writer            Alappuzha          Kerala                4   
5         Civil_servant  Tiruchirappalli[10]      Tamil_Nadu                3   
12             Designer                Adoni  Andhra_Pradesh                4   
22           Politician            Ahmedabad         Gujarat                4   

    CURRENT_HOUSE_YRS  Risk_Flag  
Id                                
1                  13          0  
3                  10          0  
5                  14          1  
12                 14          0  
22                 11          0

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = filtro[['Income', 'Age', 'Experience']]
Var_Dep = filtro['CURRENT_JOB_YRS']

#Redefinimos las variables
X = Vars_Indep
y = Var_Dep

from scipy.sparse import random
#Dividimos el conjunto de datos en la parte de entrenamiento y de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables 'X' tanto de entrenamiento como de prueba, utilizamos
X_train = escalar.fit_transform(X_train)
X_test = escalar.fit_transform(X_test)

#Definimos el algorítmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test)

from sklearn.metrics import classification_report
reporte = classification_report(y_test, y_pred, labels = [3,4])
print(reporte)

              precision    recall  f1-score   support

           3       0.53      0.65      0.58      8874
           4       0.51      0.39      0.44      8466

    accuracy                           0.52     17340
   macro avg       0.52      0.52      0.51     17340
weighted avg       0.52      0.52      0.51     17340



In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

#Cálculo de la presición del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average = 'binary', pos_label = 3)
print('\nPrecisión del modelo:')
print(precision)

#Calculo de exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculo de sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average = 'binary', pos_label = 3)
print('\nSensibilidad del modelo:')
print(sensibilidad)

#El puntaje F1 que es una combinacion entre la precisión y sensibilidad, para esto importamos f1_score
#Cálculo del puntaje F1 del modelo
from sklearn.metrics import f1_score
puntajef1 = f1_score(y_test, y_pred, average = 'binary', pos_label = 3)
print('\nPuntaje F1 del modelo:')
print(puntajef1)

Matriz de confusión:
[[5760 3114]
 [5160 3306]]

Precisión del modelo:
0.5274725274725275

Exactitud del modelo:
0.5228373702422145

Sensibilidad del modelo:
0.6490872210953347

Puntaje F1 del modelo:
0.5819945438011519


#**CASO 9**

In [ ]:
#se definen los rangos de edad en los cuáles se va a comparar cada registro
age_bins = [-1, 1, 4, 8, 12, 16, 20]

#se definen las etiquetas para cada rango de edad
age_label = [0, 4, 8, 12, 16, 20]

#el código asigna la edad del registro con el rango que corresponde de los definidos anteriormente, y dependiendo del correspondiente,
#asigna la etiqueta que corresponde al rango
df1['Experience_Range'] = pd.cut(df1['Experience'], age_bins, labels = age_label)
df1

#Convierto una variable a dicotómica
filtro = df1[(df1['Experience_Range'] == 20) | (df1['Experience_Range'] == 16)]
filtro.head()

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                          
7   3954973   58          14        married          rented            no   
9   7566849   24          17         single          rented           yes   
21  9225468   54          14         single          rented            no   
23  9157379   72          13         single          rented           yes   
24  9236505   36          19         single          rented            no   

           Profession          CITY           STATE  CURRENT_JOB_YRS  \
Id                                                                     
7           Librarian      Tiruppur      Tamil_Nadu                8   
9    Flight_attendant       Kota[6]       Rajasthan               11   
21           Surveyor  Secunderabad       Telangana                8   
23    Design_Engineer         Ajmer       Rajasthan                9   
24  Chemical_engineer        Ongole  Andhra_Pradesh                6   

    CURRENT_HOUSE_YRS  Risk_Flag Experience_Range  
Id                                                 
7                  12          0               16  
9                  11          0               20  
21                 10          0               16  
23                 10          0               16  
24                 14          0               20

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = filtro[['Income', 'Age', 'CURRENT_JOB_YRS']]
Var_Dep = filtro['Experience_Range']

#Redefinimos las variables
X = Vars_Indep
y = Var_Dep

from scipy.sparse import random
#Dividimos el conjunto de datos en la parte de entrenamiento y de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables 'X' tanto de entrenamiento como de prueba, utilizamos
X_train = escalar.fit_transform(X_train)
X_test = escalar.fit_transform(X_test)

#Definimos el algorítmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test)

from sklearn.metrics import classification_report
reporte = classification_report(y_test, y_pred, labels = [20,16])
print(reporte)

              precision    recall  f1-score   support

          20       0.51      0.53      0.52     14526
          16       0.51      0.49      0.50     14439

    accuracy                           0.51     28965
   macro avg       0.51      0.51      0.51     28965
weighted avg       0.51      0.51      0.51     28965



In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

#Cálculo de la presición del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average = 'binary', pos_label = 16)
print('\nPrecisión del modelo:')
print(precision)

#Calculo de exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculo de sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average = 'binary', pos_label = 16)
print('\nSensibilidad del modelo:')
print(sensibilidad)

#El puntaje F1 que es una combinacion entre la precisión y sensibilidad, para esto importamos f1_score
#Cálculo del puntaje F1 del modelo
from sklearn.metrics import f1_score
puntajef1 = f1_score(y_test, y_pred, average = 'binary', pos_label = 16)
print('\nPuntaje F1 del modelo:')
print(puntajef1)

Matriz de confusión:
[[7053 7386]
 [6899 7627]]

Precisión del modelo:
0.5055189220183486

Exactitud del modelo:
0.5068185741412049

Sensibilidad del modelo:
0.48846873052150425

Puntaje F1 del modelo:
0.4968475925469339


#**CASO 10**

In [ ]:
#Convierto una variable a dicotómica
filtro = df1[(df1['CITY'] == 'Saharsa[29]') | (df1['CITY'] == 'Indore')]
filtro.head()

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                           
28   9643150   24          13         single          rented            no   
88   4047079   49           7         single          rented           yes   
192   979926   61          14         single          rented           yes   
329  6518572   76          17         single           owned           yes   
533  7503211   57           6         single          rented            no   

                Profession         CITY           STATE  CURRENT_JOB_YRS  \
Id                                                                         
28                Comedian       Indore  Madhya_Pradesh                6   
88                 Dentist       Indore  Madhya_Pradesh                5   
192         Police_officer       Indore  Madhya_Pradesh                7   
329  Technology_specialist  Saharsa[29]           Bihar               14   
533              Geologist       Indore  Madhya_Pradesh                6   

     CURRENT_HOUSE_YRS  Risk_Flag Experience_Range  
Id                                                  
28                  14          0               16  
88                  14          0                8  
192                 11          1               16  
329                 12          0               20  
533                 10          0                8

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = filtro[['Income', 'Age', 'Risk_Flag']]
Var_Dep = filtro['CITY']

#Redefinimos las variables
X = Vars_Indep
y = Var_Dep

from scipy.sparse import random
#Dividimos el conjunto de datos en la parte de entrenamiento y de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables 'X' tanto de entrenamiento como de prueba, utilizamos
X_train = escalar.fit_transform(X_train)
X_test = escalar.fit_transform(X_test)

#Definimos el algorítmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test)

from sklearn.metrics import classification_report
reporte = classification_report(y_test, y_pred, labels = ['Saharsa[29]','Indore'])
print(reporte)

              precision    recall  f1-score   support

 Saharsa[29]       0.59      0.68      0.63       349
      Indore       0.62      0.53      0.57       344

    accuracy                           0.60       693
   macro avg       0.60      0.60      0.60       693
weighted avg       0.60      0.60      0.60       693



In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

#Cálculo de la presición del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average = 'binary', pos_label = 'Indore')
print('\nPrecisión del modelo:')
print(precision)

#Calculo de exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculo de sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average = 'binary', pos_label = 'Indore')
print('\nSensibilidad del modelo:')
print(sensibilidad)

#El puntaje F1 que es una combinacion entre la precisión y sensibilidad, para esto importamos f1_score
#Cálculo del puntaje F1 del modelo
from sklearn.metrics import f1_score
puntajef1 = f1_score(y_test, y_pred, average = 'binary', pos_label = 'Indore')
print('\nPuntaje F1 del modelo:')
print(puntajef1)

Matriz de confusión:
[[182 162]
 [113 236]]

Precisión del modelo:
0.6169491525423729

Exactitud del modelo:
0.6031746031746031

Sensibilidad del modelo:
0.5290697674418605

Puntaje F1 del modelo:
0.5696400625978092


#Caso de prueba (11)

In [ ]:
import math
intervalos=[-math.inf, 21, math.inf]
categorias=['Menores', 'Mayores']
df['Age_Intervalos']=pd.cut(x=df['Age'], bins=intervalos, labels=categorias)
df.head()

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                          
1   1303834   23           3         single          rented            no   
2   7574516   40          10         single          rented            no   
3   3991815   66           4        married          rented            no   
4   6256451   41           2         single          rented           yes   
5   5768871   47          11         single          rented            no   

             Profession                 CITY           STATE  CURRENT_JOB_YRS  \
Id                                                                              
1   Mechanical_engineer                 Rewa  Madhya_Pradesh                3   
2    Software_Developer             Parbhani     Maharashtra                9   
3      Technical_writer            Alappuzha          Kerala                4   
4    Software_Developer          Bhubaneswar          Odisha                2   
5         Civil_servant  Tiruchirappalli[10]      Tamil_Nadu                3   

    CURRENT_HOUSE_YRS  Risk_Flag Age_Intervalos  
Id                                               
1                  13          0        Mayores  
2                  13          0        Mayores  
3                  10          0        Mayores  
4                  12          1        Mayores  
5                  14          1        Mayores

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['Income', 'Experience']]
Var_Dep = df['Age_Intervalos']

#Redefinimos las variables
X = Vars_Indep
y = Var_Dep

from scipy.sparse import random
#Dividimos el conjunto de datos en la parte de entrenamiento y de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables 'X' tanto de entrenamiento como de prueba, utilizamos
X_train = escalar.fit_transform(X_train)
X_test = escalar.fit_transform(X_test)

#Definimos el algorítmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test)

from sklearn.metrics import classification_report
reporte = classification_report(y_test, y_pred, labels = ['Menores','Mayores'])
print(reporte)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

     Menores       0.00      0.00      0.00      1313
     Mayores       0.98      1.00      0.99     74287

    accuracy                           0.98     75600
   macro avg       0.49      0.50      0.50     75600
weighted avg       0.97      0.98      0.97     75600



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

#Cálculo de la presición del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average = 'binary', pos_label = 'Menores')
print('\nPrecisión del modelo:')
print(precision)

#Calculo de exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculo de sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average = 'binary', pos_label = 'Menores')
print('\nSensibilidad del modelo:')
print(sensibilidad)

#El puntaje F1 que es una combinacion entre la precisión y sensibilidad, para esto importamos f1_score
#Cálculo del puntaje F1 del modelo
from sklearn.metrics import f1_score
puntajef1 = f1_score(y_test, y_pred, average = 'binary', pos_label = 'Menores')
print('\nPuntaje F1 del modelo:')
print(puntajef1)

Matriz de confusión:
[[74287     0]
 [ 1313     0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Precisión del modelo:
0.0

Exactitud del modelo:
0.9826322751322751

Sensibilidad del modelo:
0.0

Puntaje F1 del modelo:
0.0


#Caso 12 (prueba)

In [ ]:
import math
intervalos = [-math.inf, 12, math.inf]
categorias = ['Altos', 'Bajos']
df['CURRENT_HOUSE_Inter'] = pd.cut(x = df['CURRENT_HOUSE_YRS'], bins = intervalos, labels = categorias)
df.head()

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                          
1   1303834   23           3         single          rented            no   
2   7574516   40          10         single          rented            no   
3   3991815   66           4        married          rented            no   
4   6256451   41           2         single          rented           yes   
5   5768871   47          11         single          rented            no   

             Profession                 CITY           STATE  CURRENT_JOB_YRS  \
Id                                                                              
1   Mechanical_engineer                 Rewa  Madhya_Pradesh                3   
2    Software_Developer             Parbhani     Maharashtra                9   
3      Technical_writer            Alappuzha          Kerala                4   
4    Software_Developer          Bhubaneswar          Odisha                2   
5         Civil_servant  Tiruchirappalli[10]      Tamil_Nadu                3   

    CURRENT_HOUSE_YRS  Risk_Flag Age_Intervalos CURRENT_HOUSE_Inter  
Id                                                                   
1                  13          0        Mayores               Bajos  
2                  13          0        Mayores               Bajos  
3                  10          0        Mayores               Altos  
4                  12          1        Mayores               Altos  
5                  14          1        Mayores               Bajos

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['Income', 'Experience', 'Risk_Flag']]
Var_Dep = df['CURRENT_HOUSE_Inter']

#Redefinimos las variables
X = Vars_Indep
y = Var_Dep

from scipy.sparse import random
#Dividimos el conjunto de datos en la parte de entrenamiento y de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables 'X' tanto de entrenamiento como de prueba, utilizamos
X_train = escalar.fit_transform(X_train)
X_test = escalar.fit_transform(X_test)

#Definimos el algorítmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test)

from sklearn.metrics import classification_report
reporte = classification_report(y_test, y_pred, labels = ['Altos','Bajos'])
print(reporte)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

       Altos       0.61      1.00      0.75     45739
       Bajos       0.00      0.00      0.00     29861

    accuracy                           0.61     75600
   macro avg       0.30      0.50      0.38     75600
weighted avg       0.37      0.61      0.46     75600



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

#Cálculo de la presición del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average = 'binary', pos_label = 'Bajos')
print('\nPrecisión del modelo:')
print(precision)

#Calculo de exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculo de sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average = 'binary', pos_label = 'Bajos')
print('\nSensibilidad del modelo:')
print(sensibilidad)

#El puntaje F1 que es una combinacion entre la precisión y sensibilidad, para esto importamos f1_score
#Cálculo del puntaje F1 del modelo
from sklearn.metrics import f1_score
puntajef1 = f1_score(y_test, y_pred, average = 'binary', pos_label = 'Bajos')
print('\nPuntaje F1 del modelo:')
print(puntajef1)

Matriz de confusión:
[[45739     0]
 [29861     0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Precisión del modelo:
0.0

Exactitud del modelo:
0.6050132275132275

Sensibilidad del modelo:
0.0

Puntaje F1 del modelo:
0.0
